/*
 * @Author: nongchatea
 * @Date: 2024-01-10 10:47:24
 * @LastEditors: nongchatea
 * @LastEditTime: 2024-01-10 15:29:40
 * @Description: ~
 */
/* eslint-disable */
/* prettier-ignore */
// @ts-nocheck
// Generated by unplugin-vue-components
// Read more: https://github.com/vuejs/core/pull/3399
export {}

declare module 'vue' {
  export interface GlobalComponents {
    RouterLink: (typeof import('vue-router'))['RouterLink'];
    RouterView: (typeof import('vue-router'))['RouterView'];
  }
}
